services:
  bitcredit:
    build: .
    environment:
      - P2P_ADDRESS=0.0.0.0
      - P2P_PORT=1909
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=8001
      - RUST_LOG=info
      - SURREAL_DB_CONNECTION=ws://surrealdb:8000
    ports:
      - "8001:8001"
      - "1909:1909"
    depends_on:
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    command:
      - start
      - --unauthenticated
    ports:
      - "8800:8000"
