name: Rust

on:
  push:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Switch rust version
        run: rustup default nightly

      - name: Update rust
        run: rustup update

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Cargo update
        run: cargo update --verbose

      - name: Check
        run: cargo check --verbose

      - name: Test
        run: cargo test
        continue-on-error: true

      - name: Build
        run: cargo build --verbose

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Add clippy
        run: rustup component add clippy

      - name: Clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
